### ISSUE TITLE
[Enhancement] Bug fixing and instruction on running test with your own image

### ISSUE THREAD

**Issue by mystvearn** [RobbieHolland/SpecialistVLMs#2]
As being reported in another issue ticket, some files are missing so the code is not running now.

In the next version of your code, it would be great if you can add instruction on how to test run on our own OCT image. I checked out the code and may guess how the data can be organized for testing. However it's still a guess. Clearer instruction would be appreciated.

**Comment by RobbieHolland** [comment]
Thank you for highlighting this - I have now created a demo that downloads and runs the model on your OCT images. You can find instructions to run it [here](https://github.com/RobbieHolland/SpecialistVLMs?tab=readme-ov-file#running-the-vlm-for-open-ended-tasks-with-demo). Alternatively, you can check this [colab](https://colab.research.google.com/drive/1IQu9JjAe23u8TFYnrEEWtuE13nZ_hf1L?usp=sharing) for an example execution, though you will need to provide your own images. Hopefully this makes running the code more straightforward!
